### ISSUE TITLE
figma_age listening on MacOS port after deleting Figma - How to uninstall / remove this

### ISSUE THREAD

**Issue by JCzz** [figma/figma-api-demo#22]
Hi

I have had Figma installed on MacOs and removed it again - now I have a figma_age(lsof -i ) command running listening on port 44950 and 44960.

Thanks

**Comment by alanmaciel** [comment]
I had the figma_age listening too after uninstalling Figma on MacOS, I just killed the process using the PID, maybe that can help you in the meantime.

**Comment by timglorioso** [comment]
I ran `find / -name "*figma*"` to see if there were remnants from the installation, found some stuff in Application Support and the like. After getting rid of those and rebooting, `figma_age` seems to not run anymore.

**Comment by juanuicich** [comment]
The FigmaAgent comes back when you update the app. This should be a setting. But meanwhile:

> This seems to work for removing FigmaAgent:
> • Force Quit it in Activity Monitor
> • Remove it in System Preferences > Users & Groups > Login Items
> • Delete ~/Library/Application Support/Figma/FigmaAgent.app
> • Delete /Applications/Figma.app/Contents/Library/FigmaAgent.app

Source: https://twitter.com/qdoug/status/1374785043504185351

**Comment by ivn-svn** [comment]
So did anyone find out what it listens for?

**Comment by Baltsat** [comment]
> So did anyone find out what it listens for?
No, it is still a mystery. But very interesting to find out.
