### ISSUE TITLE
Is there a way to perform the "Resize To Fit" functionality

### ISSUE THREAD

**Issue by tatemz** [figma/figma-api-demo#32]
I'm looking for a way to programmatically run the same functionality as the `resize-to-fit` action. Is there an easy way to do this with the Figma API?

![image](https://user-images.githubusercontent.com/2190655/115927468-18783b80-a44a-11eb-8912-d91cf348d696.png)

**Comment by tatemz** [comment]
Leaving this note here: I was able to get my use-case 50% of the way there by using `figma.group` which will autosize to fit  based on its grouped children. I am now looking for a way to seamlessly convert a `GroupNode` to a `FrameNode` using the API

**Comment by artfabrique** [comment]
Group does not include Effects
