### ISSUE TITLE
No license file here

### ISSUE THREAD

**Issue by Logiraptor** [figma/figma-api-demo#4]
Hi!

I'm interested in adapting the figma-to-react code to cover some more use cases / support typescript as a compile target / etc. Just wondering if you could add a license to this repo so the community can give proper attribution in the case of any borrowed code. I interpret this repo to be for exactly that purpose, so I'd expect any license to be relatively open. Just want to make sure there's no risk in basing work off the code here.

**Comment by MatthewDailey** [comment]
This repo is released under the MIT license. License file added in https://github.com/figma/figma-api-demo/pull/5

Thanks for flagging!
