### ISSUE TITLE
Undocumented api usage in figma-to-react demo

### ISSUE THREAD

**Issue by Logiraptor** [figma/figma-api-demo#6]
I've been converting the figma-to-react demo to typescript before making more substantial changes, and I've found some inconsistencies in the api usage here vs the documentation. 

The code references an `imageHash` property on a `Paint` instance with type == 'IMAGE', but I don't see any reference to that property in the docs here: https://www.figma.com/developers/docs#fileformat

Sorry if this is the wrong place to report this. Is there a more suitable place to discuss the design of the figma-to-react demo?

**Comment by Logiraptor** [comment]
Looks like the usage of `rectangleCornerRadii` is also undocumented here: https://github.com/figma/figma-api-demo/blob/master/figma-to-react/lib/figma.js#L280

**Comment by MatthewDailey** [comment]
Opened a PR to the docs to address missing `rectangleCornerRadii`. Thanks so much for flagging this!
