### ISSUE TITLE
'imageHash' is undefined

### ISSUE THREAD

**Issue by denissamoilov** [figma/figma-api-demo#8]
@MatthewDailey @0000marcell ,

**lib/figma.js**
```
} else if (lastFill.type === 'IMAGE') {
            styles.backgroundImage = imageURL(lastFill.imageHash);
```

I believe Figma have updated their API, now 'imageHash' is undefined, instead of it I've found out that it's new name is 'imageRef'.

**Comment by glebkudr** [comment]
The same for me :(

**Comment by denissamoilov** [comment]
> The same for me :(

use 'imageRef' instead of 'imageHash'.
