### ISSUE TITLE
Is figma-to-react production ready?

### ISSUE THREAD

**Issue by tb** [figma/figma-api-demo#9]
The tool is contained within figma-api-demo repo and the repo is not active since https://blog.figma.com/introducing-figma-to-react-d2d545cba3cc was published back in May.

I also checked https://www.figma.com/customers Success Stories and I was not able a word about "React" there.

**Comment by MatthewDailey** [comment]
No the `figma-to-react` is intended as a demo project to serve as inspiration for what can be done with the Figma API. 

If you are interested in expanding it to a production-ready product and have questions about the API please reach out! We're happy to help!
